DESC MEMBER;
INSERT INTO MEMBER(MEMBER_ID, MEMBER_PWD,MEMBER_NAME,MEMBER_EMAIL,MEMBER_CELLPHONE,MEMBER_TEL,
MEMBER_ADDRESS_POST,MEMBER_ADDRESS_1,MEMBER_ADDRESS_2,MEMBER_BIRTHDAY,MEMBER_EMAIL_AGREE,MEMBER_SMS_AGREE)
VALUES ('aaa','aaa123', '이름', 'aaa1@gmail.com', '01000000000', '020000000', '우편번호','주소1','주소2', SYSDATE, 1,1)
;

DESC BOARD_CATEGORY;
INSERT INTO BOARD_CATEGORY (BOARD_CATEGORY_CODE,BOARD_CATEGORY_NAME)
VALUES (1,'문의내용', '회원/정보관리', '주문/결제', '배송', '반품/환불/교환/AS', '영수증/증빙서류', '상품/이벤트', '기타')
;

DESC BOARD;
INSERT INTO BOARD(BOARD_NO,BOARD_TITLE,BOARD_CONTENT,BOARD_WRITER,BOARD_DATE,BOARD_CATEGORY_CODE)
VALUES ((SELECT NVL(MAX(BOARD_NO),0)+1 FROM BOARD),'제목','내용CLOB','박민지','')
;

--BOARD_NO            NOT NULL NUMBER       
--BOARD_TITLE         NOT NULL VARCHAR2(50) 
--BOARD_CONTENT       NOT NULL CLOB ------------> 강의보면서 하기        
--BOARD_WRITER        NOT NULL VARCHAR2(30) 
--BOARD_DATE          NOT NULL TIMESTAMP(6) 
--BOARD_CATEGORY_CODE NOT NULL NUMBER(2)    

DESC BOARD_FILE;
INSERT INTO BOARD_FILE (BOARD_FILEPATH,BOARD_NO)
VALUES ('첨부파일')
;
--BOARD_FILEPATH NOT NULL VARCHAR2(500) 
--BOARD_NO       NOT NULL NUMBER   

DESC PRODUCT;
INSERT INTO PRODUCT (PRODUCT_ID,PRODUCT_NAME,PRODUCT_PRICE,PRODUCT_DETAIL)
VALUES ()
;

--PRODUCT_ID     NOT NULL NUMBER        
--PRODUCT_NAME   NOT NULL VARCHAR2(300) 
--PRODUCT_PRICE  NOT NULL NUMBER        
--PRODUCT_DETAIL NOT NULL CLOB  

DESC PRODUCT_IMAGE;
INSERT INTO PRODUCT_IMAGE (PRODUCT_IMAGE_CODE,PRODUCT_CODE)
VALUES ()
;

--PRODUCT_IMAGE_CODE NOT NULL VARCHAR2(500) 
--PRODUCT_CODE       NOT NULL NUMBER  